import Head from "next/head"
import { useEffect, useState } from "react";
import Header from "../components/Header"
import { data } from "../public/lib/data"

function technology() {


    const [index, setIndex] = useState(0);
    const [dispData, setDispData] = useState(data.technology[0]);

    useEffect(()=>{
        setDispData(data.technology[index])
    }, [index])

    return (
        <div className='bg-technology bg-no-repeat bg-cover min-h-screen py-[40px] pb-[80px] gap-[40px] flex flex-col items-center'>
            <Head>
				<title>Space Travel</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com"/>
				<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
				<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@100;400&family=Bellefair&display=swap" rel="stylesheet" />
			</Head>
            <Header />
            <div className="xl:max-w-[77rem] w-full ml-auto flex-1 flex flex-col items-center justify-center xl:justify-start xl:items-start gap-[40px] xl:gap-[20px]">
                <p className="barlow-condensed text-[20px] xl:text-[28px] text-[#d0d6f9] tracking-widest"><span className="font-[700] text-[#52555c]">03</span>&nbsp;&nbsp;&nbsp;&nbsp;SPACE LAUNCH 101</p>
                <div className="grow flex flex-col gap-[40px] xl:grid xl:grid-cols-2 xl:gap-[100px]">
                    <div className="block xl:hidden flex items-center justify-center"><img src= {`${"/assets/technology/image-"+ dispData?.name?.toLowerCase().split(" ").join("-")+"-landscape.jpg"}`} alt='' className="w-[100%]"/></div>
                    <div className="flex items-center justify-between gap-[60px]">
                        <div className="flex flex-col px-[20px] items-center justify-center xl:px-0 xl:flex-row gap-[30px] xl:gap-[60px]">
                            <div className="h-max flex xl:flex-col items-center justify-center gap-[20px] xl:gap-[40px]">
                                <div className={`${index===0?"bg-white text-[#0B0D17]":null} rounded-full border-[1px] border-[#52555c] py-[9px] xl:py-[13px] px-[20px] xl:px-[28px] bellefair text-[21px] xl:text-[30px] hover:bg-white hover:text-[#0B0D17] cursor-pointer transition-all duration-300`} onClick={() => {setIndex(0)}}>
                                    1
                                </div>
                                <div className={`${index===1?"bg-white text-[#0B0D17]":null} rounded-full border-[1px] border-[#52555c] py-[9px] xl:py-[13px] px-[20px] xl:px-[28px] bellefair text-[21px] xl:text-[30px] hover:bg-white hover:text-[#0B0D17] cursor-pointer transition-all duration-300`} onClick={() => {setIndex(1)}}>
                                    2
                                </div>
                                <div className={`${index===2?"bg-white text-[#0B0D17]":null} rounded-full border-[1px] border-[#52555c] py-[9px] xl:py-[13px] px-[20px] xl:px-[28px] bellefair text-[21px] xl:text-[30px] hover:bg-white hover:text-[#0B0D17] cursor-pointer transition-all duration-300`} onClick={() => {setIndex(2)}}>
                                    3
                                </div>
                            </div>
                            <div className="flex-1 flex flex-col gap-[20px] items-center justify-center xl:items-start xl:justify-between">
                                <div className="flex flex-col items-center xl:items-start justify-center gap-[10px] xl:gap-0">
                                    <p className="barlow-condensed text-[#d0d6f9] text-[18px] tracking-widest">THE TERMINOLOGY...</p>
                                    <div className="bellefair text-[28px] xl:text-[40px] ">
                                        <p>{dispData?.name?.toUpperCase()}</p>
                                    </div>
                                </div>
                                
                                <div className="barlow-condensed flex text-center xl:text-left">
                                    <p className="text-[20px] text-[#d0d6f9]">
                                        {/* A launch vehicle or carrier rocket is a rocket-propelled vehicle used to carry a 
                                        payload from Earth's surface to space, usually to Earth orbit or beyond. Our 
                                        WEB-X carrier rocket is the most powerful in operation. Standing 150 metres tall, 
                                        it's quite an awe-inspiring sight on the launch pad! */}
                                        {dispData?.description}
                                    </p>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                    <div className={`hidden xl:block ${dispData.name.split(" ")[0].toLowerCase()} bg-no-repeat bg-cover`}>
                        {/* <img src ="/assets/technology/image-launch-vehicle-portrait.jpg" /> */}
                        
                    </div>
                </div>
            </div>
           
        </div>
    )
}

export default technology
